### PR TITLE
Change default-directory to load edn, and edn point to local repo

### PR DESCRIPTION
**Pull request by kimim**
1. change `default-derectory` to load edn
2. point deps to local repo for testing

### CODE REVIEW

**Comment by kimim** [comment]
deps in demo/deps.edn is out of sync. point it to :local/root to avoid mismatch.

**Comment by kimim** [comment]
clojure likes to execute in the project directory as default, so it is better to temporary change default-directory for it.

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/reorder-file

我开发的应用， 也需要用 ‘local/root’ 吗？

**Comment by kimim** [comment]
那不需要了。
我少执行了一次
```
clojure -X:jar
clojure -X:install
```

I'll fix it.

**Comment by manateelazycat** [comment]
感谢大佬补丁

**Pull request merged**
